# Generated by Django 2.2.6 on 2019-11-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191101_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(related_name='list_products', to='app.Product'),
        ),
    ]
